version: '3.9'

services:
  spring-boot:
    image: sentinel-image
    container_name: sentinel-container
    ports:
      - "8080:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge